name: Deploy Next.js application
on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: buat file .env
        run: |
          echo "CLERK_SECRET_KEY=${{secrets.CLERK_SECRET_KEY}}" >> .env
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}" >> .env
          echo "NEXT_PUBLIC_CONVEX_URL=${{secrets.NEXT_PUBLIC_CONVEX_URL}}" >> .env
          echo "CONVEX_DEPLOYMENT=${{secrets.CONVEX_DEPLOYMENT}}" >> .env
          echo "SITE_URL=${{secrets.SITE_URL}}" >> .env
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: shanealexander09/pso-chat-docker:latest
  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20.9.0
      - name: install jest dll
        run: npm install
      - name: Run tests
        run:
          npm test
          ##deploy dockerhub

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.5
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TF_USER_AWS_KEY }}
          aws-secret-access-key: ${{secrets.TF_USER_AWS_SECRET}}
          aws-region: ap-southeast-2

      - name: Initialize Terraform
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=plan.out
      - name: Terraform Apply
        run: terraform apply plan.out
        env:
          TF_VAR_access_key: ${{ secrets.TF_USER_AWS_KEY }}
          TF_VAR_secret_key: ${{ secrets.TF_USER_AWS_SECRET }}

      - name: Get Instance IP
        id: instance_ip
        run: |
          INSTANCE_IP=$(terraform output -raw instance_ip)
          echo "::set-output name=instance_ip::$INSTANCE_IP"
          echo "TEST=$INSTANCE_IP" >> $GITHUB_ENV
          echo ${{ env.INSTANCE_IP }}

      - name: Debug Instance IP
        run: echo "Instance IP is ${{env.INSTANCE_IP}}"

      - name: Push Docker Image to EC2 Instance
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@${{ env.INSTANCE_IP }} 'docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}'
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@${{ env.INSTANCE_IP }} 'docker pull shanealexander09/pso-chat-docker:latest'
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@${{ env.INSTANCE_IP }} 'docker run -d -p 3000:3000 shanealexander09/pso-chat-docker:latest'
